on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Git Repository'
        uses: actions/checkout@v2

      - name: 'Add secrets to repository'
        run: echo '${{secrets.LOCAL_CONFIG}}' > config/local.json

      - name: 'Install modules'
        run: npm i

      - name: 'Run tests'
        run: npm t